<!ELEMENT tienda (inventario)>
<!ATTLIST tienda 
          nombre CDATA #REQUIRED
          ubicacion CDATA #REQUIRED>

<!ELEMENT inventario (fabricante+)>
<!ATTLIST inventario 
          categoria CDATA #REQUIRED
          fechaActualizacion CDATA #REQUIRED>

<!ELEMENT fabricante (chip+)>
<!ATTLIST fabricante 
          nombre (Intel | AMD) #REQUIRED
          arquitectura CDATA #REQUIRED>

<!ELEMENT chip (modelo, especificaciones, precio, stock_actual, fechaRegistro)>
<!ATTLIST chip 
          id ID #REQUIRED
          destacado (true | false) #REQUIRED
          disponible (true | false) #REQUIRED>

<!ELEMENT modelo (#PCDATA)>

<!ELEMENT especificaciones (nucleos_hilos, socket, frecuencia)>
<!ELEMENT nucleos_hilos (#PCDATA)>
<!ELEMENT socket (#PCDATA)>

<!ELEMENT frecuencia (#PCDATA)>
<!ATTLIST frecuencia 
          unidad CDATA #FIXED "GHz">

<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio 
          moneda CDATA #FIXED "EUR">

<!ELEMENT stock_actual (#PCDATA)>
<!ELEMENT fechaRegistro (#PCDATA)>