<!ELEMENT unidades_alimentacion (inventario)>
<!ATTLIST unidades_alimentacion 
          tienda CDATA #REQUIRED>

<!ELEMENT inventario (fabricante+)>
<!ATTLIST inventario 
          categoria CDATA #REQUIRED
          fechaActualizacion CDATA #REQUIRED>

<!ELEMENT fabricante (fuente+)>
<!ATTLIST fabricante 
          nombre CDATA #REQUIRED>

<!ELEMENT fuente (modelo, especificaciones, precio, estado, fechaRegistro)>
<!ATTLIST fuente 
          id ID #REQUIRED
          gama CDATA #IMPLIED
          modular (true | false) #REQUIRED
          disponible (true | false) #IMPLIED>

<!ELEMENT modelo (#PCDATA)>

<!ELEMENT especificaciones (potencia, certificacion)>

<!ELEMENT potencia (#PCDATA)>
<!ATTLIST potencia 
          unidad CDATA #FIXED "W">

<!ELEMENT certificacion (#PCDATA)>

<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio 
          moneda CDATA #FIXED "EUR">

<!ELEMENT estado (#PCDATA)>
<!ELEMENT fechaRegistro (#PCDATA)>