<!ELEMENT tienda (inventario)>
<!ATTLIST tienda 
          nombre CDATA #REQUIRED
          ubicacion CDATA #IMPLIED>

<!ELEMENT inventario (fabricante+)>
<!ATTLIST inventario 
          categoria CDATA #REQUIRED
          fechaActualizacion CDATA #REQUIRED>

<!ELEMENT fabricante (tarjeta+)>
<!ATTLIST fabricante 
          nombre (NVIDIA | AMD) #REQUIRED>

<!ELEMENT tarjeta (modelo, especificaciones, precio, fechaRegistro)>
<!ATTLIST tarjeta 
          id ID #REQUIRED
          disponible (true | false) #REQUIRED>

<!ELEMENT modelo (#PCDATA)>

<!ELEMENT especificaciones (vram, interfaz, consumo)>
<!ELEMENT vram (#PCDATA)>
<!ATTLIST vram 
          unidad CDATA #FIXED "GB"
          tipo (GDDR6 | GDDR6X) #REQUIRED>

<!ELEMENT interfaz (#PCDATA)>
<!ATTLIST interfaz unidad CDATA #FIXED "bit">

<!ELEMENT consumo (#PCDATA)>
<!ATTLIST consumo unidad CDATA #FIXED "W">

<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio moneda CDATA #FIXED "EUR">

<!ELEMENT fechaRegistro (#PCDATA)>