<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="almacenamiento_volatil">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="inventario">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="fabricante" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="modulo" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="modelo" type="xs:string"/>
                          <xs:element name="especificaciones">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="capacidad">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:integer">
                                        <xs:attribute name="unidad" type="xs:string" fixed="GB"/>
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="configuracion" type="xs:string"/>
                                <xs:element name="frecuencia">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:integer">
                                        <xs:attribute name="unidad" type="xs:string" fixed="MHz"/>
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="precio">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:decimal">
                                  <xs:attribute name="moneda" type="xs:string" fixed="EUR"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="estado">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:integer">
                                  <xs:attribute name="disponible" type="xs:boolean" use="required"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="fechaRegistro" type="xs:date"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:ID" use="required"/>
                        <xs:attribute name="tecnologia" type="xs:string" use="required"/>
                        <xs:attribute name="rgb" type="xs:boolean" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="nombre" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="categoria" type="xs:string" use="required"/>
            <xs:attribute name="fechaActualizacion" type="xs:date" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="tienda" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

</xs:schema>