<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="perifericos_puntero">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="inventario">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="fabricante" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="raton" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="modelo" type="xs:string"/>
                          <xs:element name="especificaciones">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="dpi_max">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:integer">
                                        <xs:attribute name="unidad" type="xs:string" fixed="DPI"/>
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="peso">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute name="unidad" type="xs:string" fixed="g"/>
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="precio" type="xs:decimal"/>
                          <xs:element name="fechaRegistro" type="xs:date"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:ID" use="required"/>
                        <xs:attribute name="conexion" type="xs:string"/>
                        <xs:attribute name="disponible" type="xs:boolean" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="nombre" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="categoria" type="xs:string" use="required"/>
            <xs:attribute name="fechaActualizacion" type="xs:date" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="nombre" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>